-- +goose Up
INSERT INTO dictionaries (id, code, name, category, description, items_json)
VALUES
  ('DICT-EMR-FIELDS', 'emr_common_fields', '电子病历常用字段', '电子病历', '门诊、住院、专科病历同步和表单映射常用字段', CAST('[{"key":"record_no","label":"病历号","value":"record_no"},{"key":"record_type","label":"病历类型","value":"record_type"},{"key":"record_title","label":"病历标题","value":"record_title"},{"key":"chief_complaint","label":"主诉","value":"chief_complaint"},{"key":"present_illness","label":"现病史","value":"present_illness"},{"key":"past_history","label":"既往史","value":"past_history"},{"key":"personal_history","label":"个人史","value":"personal_history"},{"key":"allergy_history","label":"过敏史","value":"allergy_history"},{"key":"physical_exam","label":"体格检查","value":"physical_exam"},{"key":"specialist_exam","label":"专科检查","value":"specialist_exam"},{"key":"auxiliary_exam","label":"辅助检查","value":"auxiliary_exam"},{"key":"diagnosis_code","label":"诊断编码","value":"diagnosis_code"},{"key":"diagnosis_name","label":"诊断名称","value":"diagnosis_name"},{"key":"treatment_plan","label":"诊疗计划","value":"treatment_plan"},{"key":"doctor_advice","label":"医嘱","value":"doctor_advice"},{"key":"recorded_at","label":"记录时间","value":"recorded_at"},{"key":"record_doctor","label":"记录医生","value":"record_doctor"},{"key":"department_code","label":"科室编码","value":"department_code"},{"key":"department_name","label":"科室名称","value":"department_name"},{"key":"source_system","label":"来源系统","value":"source_system"}]' AS JSON)),
  ('DICT-CASE-FIELDS', 'case_common_fields', '病例常用字段', '病例管理', '病例建档、科研队列、病案首页和随访筛选常用字段', CAST('[{"key":"case_no","label":"病例号","value":"case_no"},{"key":"patient_no","label":"档案号","value":"patient_no"},{"key":"patient_name","label":"患者姓名","value":"patient_name"},{"key":"gender","label":"性别","value":"gender"},{"key":"age","label":"年龄","value":"age"},{"key":"id_card_no","label":"身份证号","value":"id_card_no"},{"key":"phone","label":"联系电话","value":"phone"},{"key":"case_source","label":"病例来源","value":"case_source"},{"key":"disease_code","label":"病种编码","value":"disease_code"},{"key":"disease_name","label":"病种名称","value":"disease_name"},{"key":"primary_diagnosis_code","label":"主要诊断编码","value":"primary_diagnosis_code"},{"key":"primary_diagnosis_name","label":"主要诊断名称","value":"primary_diagnosis_name"},{"key":"tumor_stage","label":"肿瘤分期","value":"tumor_stage"},{"key":"pathology_no","label":"病理号","value":"pathology_no"},{"key":"pathology_diagnosis","label":"病理诊断","value":"pathology_diagnosis"},{"key":"operation_name","label":"手术名称","value":"operation_name"},{"key":"operation_date","label":"手术日期","value":"operation_date"},{"key":"discharge_status","label":"出院情况","value":"discharge_status"},{"key":"followup_flag","label":"随访标识","value":"followup_flag"},{"key":"case_created_at","label":"建档时间","value":"case_created_at"}]' AS JSON)),
  ('DICT-VISIT-FIELDS', 'visit_common_fields', '就诊常用字段', '就诊信息', '门诊、急诊、住院、出院记录同步常用字段', CAST('[{"key":"visit_no","label":"就诊号","value":"visit_no"},{"key":"visit_type","label":"就诊类型","value":"visit_type"},{"key":"outpatient_no","label":"门诊号","value":"outpatient_no"},{"key":"inpatient_no","label":"住院号","value":"inpatient_no"},{"key":"admission_no","label":"入院登记号","value":"admission_no"},{"key":"visit_at","label":"就诊时间","value":"visit_at"},{"key":"admission_at","label":"入院时间","value":"admission_at"},{"key":"discharge_at","label":"出院时间","value":"discharge_at"},{"key":"department_code","label":"就诊科室编码","value":"department_code"},{"key":"department_name","label":"就诊科室","value":"department_name"},{"key":"ward_name","label":"病区","value":"ward_name"},{"key":"bed_no","label":"床号","value":"bed_no"},{"key":"attending_doctor","label":"主治医生","value":"attending_doctor"},{"key":"responsible_nurse","label":"责任护士","value":"responsible_nurse"},{"key":"diagnosis_code","label":"就诊诊断编码","value":"diagnosis_code"},{"key":"diagnosis_name","label":"就诊诊断","value":"diagnosis_name"},{"key":"visit_status","label":"就诊状态","value":"visit_status"},{"key":"discharge_disposition","label":"离院方式","value":"discharge_disposition"},{"key":"total_fee","label":"总费用","value":"total_fee"},{"key":"insurance_type","label":"医保类型","value":"insurance_type"}]' AS JSON)),
  ('DICT-MEDICATION-FIELDS', 'medication_common_fields', '用药常用字段', '用药信息', '处方、医嘱、用药随访和不良反应采集常用字段', CAST('[{"key":"order_no","label":"医嘱号","value":"order_no"},{"key":"prescription_no","label":"处方号","value":"prescription_no"},{"key":"drug_code","label":"药品编码","value":"drug_code"},{"key":"drug_name","label":"药品名称","value":"drug_name"},{"key":"generic_name","label":"通用名","value":"generic_name"},{"key":"specification","label":"规格","value":"specification"},{"key":"dosage","label":"单次剂量","value":"dosage"},{"key":"dosage_unit","label":"剂量单位","value":"dosage_unit"},{"key":"frequency","label":"用药频次","value":"frequency"},{"key":"route","label":"给药途径","value":"route"},{"key":"start_at","label":"开始时间","value":"start_at"},{"key":"end_at","label":"结束时间","value":"end_at"},{"key":"days","label":"用药天数","value":"days"},{"key":"quantity","label":"数量","value":"quantity"},{"key":"manufacturer","label":"生产厂家","value":"manufacturer"},{"key":"doctor_name","label":"开立医生","value":"doctor_name"},{"key":"pharmacist_name","label":"审核药师","value":"pharmacist_name"},{"key":"medication_status","label":"用药状态","value":"medication_status"},{"key":"adverse_reaction","label":"不良反应","value":"adverse_reaction"},{"key":"compliance","label":"用药依从性","value":"compliance"}]' AS JSON))
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  category = VALUES(category),
  description = VALUES(description),
  items_json = VALUES(items_json);

-- +goose Down
DELETE FROM dictionaries
WHERE id IN ('DICT-EMR-FIELDS', 'DICT-CASE-FIELDS', 'DICT-VISIT-FIELDS', 'DICT-MEDICATION-FIELDS');
